model: vllm
tasks: hellaswag
model_args: pretrained=/data/wlj/pretrained/Qwen/Qwen3-0.6B
num_fewshot: null
batch_size: '8'
max_batch_size: null
device: cuda:0
output_path: null
limit: null
samples: null
use_cache: null
cache_requests: null
check_integrity: false
write_out: false
log_samples: false
system_instruction: null
apply_chat_template: false
fewshot_as_multiturn: false
show_config: false
include_path: null
gen_kwargs: null
verbosity: null
wandb_args: ''
wandb_config_args: ''
hf_hub_log_args: ''
predict_only: false
seed:
- 0
- 1234
- 1234
- 1234
trust_remote_code: false
confirm_run_unsafe_code: false
metadata: null
